import { RouletteData } from './types';

export const ROULETTE_DATA: RouletteData[] = [
  {
    type: 'tool',
    title: '🎨 Tool',
    color: '#FF6B35',
    optional: false,
    options: [
      'Oil Paint',
      'Watercolor',
      'Pencil',
      'Pen & Ink',
      'Pastel',
      'Charcoal',
      'Colored Pencil',
      'Acrylic Paint',
    ],
  },
  {
    type: 'style',
    title: '🖼️ Style',
    color: '#9B59B6',
    optional: false,
    options: [
      'Realism',
      'Impressionism',
      'Abstract',
      'Surrealism',
      'Cubism',
      'Pop Art',
      'Minimalism',
      'Expressionism',
      'Art Nouveau',
      'Street Art',
    ],
  },
  {
    type: 'subject',
    title: '🏞️ Subject',
    color: '#3498DB',
    optional: false,
    options: [
      'Portrait',
      'Landscape',
      'Still Life',
      'Animals',
      'Architecture',
      'Fantasy Scene',
      'Everyday Object',
      'Abstract Concept',
      'Nature Detail',
      'Urban Scene',
    ],
  },
  {
    type: 'support',
    title: '📄 Support',
    color: '#2ECC71',
    optional: true,
    options: [
      'Canvas',
      'Paper',
      'Wood Panel',
      'Sketchbook',
      'Cardboard',
      'Toned Paper',
      'Watercolor Paper',
    ],
  },
  {
    type: 'time',
    title: '⏱️ Time Limit',
    color: '#F39C12',
    optional: true,
    options: [
      '5 min',
      '10 min',
      '15 min',
      '20 min',
      '30 min',
      '45 min',
      '60 min',
      '90 min',
    ],
  },
  {
    type: 'twist',
    title: '✨ Twist',
    color: '#E74C3C',
    optional: true,
    options: [
      '🦆 A Duck',
      '😄 A Minion',
      '🐱 A Hidden Cat',
      '🤖 A Tiny Robot',
      '👁️ Googly Eyes',
      '🌈 A Rainbow',
      '👻 A Ghost',
      '⭐ Hidden Stars',
      '🎈 A Balloon',
      '🦋 A Butterfly',
    ],
  },
];

export const SPIN_DURATION = 2500; // milliseconds
export const SPIN_STAGGER_DELAY = 200; // milliseconds between each wheel when spinning all
